// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owwcztcfqmkkooiwmnwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93d2N6dGNmcW1ra29vaXdtbndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzcyMTksImV4cCI6MjA2NzA1MzIxOX0.6TJoLoqtTDD3I-nkEgqSEvRfpYl2vvHjwlofwBxINos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});